config/routes.rb
Rails.application.routes.draw do
  get 'def/send_mail'

  root to: 'pages#home'
  get '/about' => 'pages#about'
  get '/services' => 'pages#services'
  get '/soccer' => 'pages#soccer'
  get '/basketball' => 'pages#basketball'
  get '/mma' => 'pages#mma'
  get '/football' => 'pages#football'
  get '/sports-marketing' => 'pages#sports-marketing'
  get '/clients' => 'pages#clients'
  get '/contact' => 'pages#contact'
  get '/media' => 'pages#media'

  resources :contact
  match '/send_mail', to: 'contact#send_mail', via: 'post'

  devise_for :users
  resources :users
end

app/models/contact.rb
class Contact < MailForm::Base
  attribute :name,      :validate => true
  attribute :email,     :validate => /\A([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})\z/i
  attribute :message
  attribute :nickname,  :captcha  => true

  # Declare the e-mail headers. It accepts anything the mail method
  # in ActionMailer accepts.
  def headers
    {
      :subject => "My Contact Form",
      :to => "your_email@example.org",
      :from => %("#{name}" <#{email}>)
    }
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  def new
    @contact = Contact.new
  end

  def create
    @contact = Contact.new(params[:contact])
    @contact.request = request
    if @contact.deliver
      flash.now[:error] = nil
      flash.now[:notice] = 'Thank you for your message!'
    else
      flash.now[:error] = 'Cannot send message.'
      render :new
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

	def home
	end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    unless @user == current_user
      redirect_to :back, :alert => "Access denied."
    end
  end

end

app/controllers/visitors_controller.rb
class VisitorsController < ApplicationController

end

app/helpers/application_helper.rb
module ApplicationHelper

	def title(page_title)
  		content_for :title, page_title.to_s
	end

	def nav_link(link_text, link_path)
  		class_name = current_page?(link_path) ? 'active' : ''

  		content_tag(:li, :class => class_name) do
    		link_to link_text, link_path
  		end
	end

end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/contacts/create.html.erb
<h1>Thank you for your message.</h1>
<p>We'll get back to you soon.</p>

app/views/contacts/new.html.erb
<div class="container">
  <h1>Contact</h1>
  <%= simple_form_for @contact, :html => {:class => 'form-horizontal' } do |f| %>
  <%= f.input :name, :required => true %>
  <%= f.input :email, :required => true %>
  <%= f.input :message, :as => :text, :required => false, :input_html => {:rows => 10} %>
  <div class="hidden">
    <%= f.input :nickname, :hint => 'Leave this field blank!' %>
  </div>
  <div class="form-actions">
    <%= f.button :submit, 'Send message', :class=> "btn btn-primary" %>
  </div>
  <% end %>
</div>

app/views/layouts/_footer.html.erb
<section class="footer-13">
  <div class="container">
    <div class="row">
      <div class="col-md-2 col-md-offset-1">
        <div class="overlay-facebook">
          <a href="#"><i class="fa fa-facebook fa-3x"></i></a>
        </div>
      </div>
      <div class="col-md-2">
        <div class="overlay-twitter">
          <a href="#"><i class="fa fa-twitter fa-3x"></i></a>
        </div>
      </div>
      <div class="col-md-2">
        <div class="overlay-youtube">
          <a href="#"><i class="fa fa-youtube fa-3x"></i></a>
        </div>
      </div>
      <div class="col-md-2">
        <div class="overlay-linkedin">
          <a href="#"><i class="fa fa-linkedin fa-3x"></i></a>
        </div>
      </div>
      <div class="col-md-2">
        <div class="overlay-mogo">
          <a href="#"><a href="#"><i class="fa fa-facebook fa-3x"></i></a>
        </div>
      </div>
    </div>
  </div>
</section>
<section class="footer-2 bg-black">
  <div class="container">
    <nav class="pull-left">
      <p>© 2015 - All Rights Reserved</p>
    </nav>
    <div class="social-btns pull-right">
      Designed with &hearts; in miami by stilt media
    </div>
  </div>
</section>

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<div class="container-fluid">
    <div class="row">
        <div class="navbar navbar-fixed-top" id="navbar">
            <div class="nav-user">
            <ul class="nav">
            <%= link_to image_tag('logo-sm.png'), root_path, class: 'nav-apply' %>
            </ul>
            </div>
            <button type="button" class="navbar-toggle">
            <span>MENU</span>
            <div>CLOSE</div>
            </button>
            <div class="navbar-collapse collapse">
                <%= render 'layouts/navigation_links' %>
            </div>
        </div>
    </div>
</div>

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>
<ul class="nav">                  
	<li><%= nav_link 'Home', root_path %></li>
	<li><%= nav_link 'About', about_path %></li>
	<li><%= nav_link 'Services', services_path %></li>
	<li><%= nav_link 'Soccer', soccer_path %></li>
	<li><%= nav_link 'Basketball', basketball_path %></li>
	<li><%= nav_link 'MMA', mma_path %></li>
	<li><%= nav_link 'Football', football_path %></li>
	<li><%= nav_link 'Sports Marketing', sports_marketing_path %></li>
	<li><%= nav_link 'Clients', clients_path %></li>
	<li><%= nav_link 'Contact', contact_path %></li>
	<li><%= nav_link 'Media', media_path %></li>
	<% if user_signed_in? %>
	  <li><%= link_to 'Edit account', edit_user_registration_path %></li>
	  <li><%= link_to 'Sign out', destroy_user_session_path, :method=>'delete' %></li>
	<% else %>
	  <li><%= link_to 'Sign in', new_user_session_path %></li>
	<% end %>
	<% if user_signed_in? %>
	  <li><%= link_to 'Users', users_path %></li>
	<% end %>  
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= yield(:title) %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Paradigm Sports Management" %>">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <div class="page-wrapper">  
      <header class="header-16" id="header">
        <%= render 'layouts/navigation' %>
      </header>
  
      <%= yield %>

      <footer>
        <%= render 'layouts/footer' %>
      </footer>

    </div>
  </body>
</html>

app/views/pages/about.html.erb
<% title "About | Paradigm Sports Management" %>

<section class="header-16-sub home-content home-content-header about" id="header-content">
	<div class="background"></div>
	<div id="h-16-pt-main" class="page-transitions pt-perspective">
		<div class="v-center pt-page pt-page-1 pt-page-current">
			<div>
				<div class="container">
					<div class="hero-unit">
						<div id="logo-main">
							<h3>LEARN MORE OF</h3>
							<h1>WHAT WE DO</h1>
						</div>
					</div>
				</div>
			</div>
			<span class="scroll-btn">
				<a href="#">
					<span class="mouse"><span> </span>
					</span>
				</a>
			</span>
		</div>
	</div>
</section>
<section class="content-32-about">
    <div class="container">
        <div class="row">
            <div class="col-sm-10 col-sm-offset-1">
                <h3>PARADIGM PHILOSOPHY</h3>
                <p>"Together Everyone Achieves More" - a mantra taught throughout sports and what we at Paradigm Sports Management emulate in our operations and management. Paradigm Sports Management breaks the conventional approach to offer a unique level of service that emulates our clients’ discipline, passion, and determination on their respective playing field.  It starts and ends with our clients well being and satisfaction, we do not rest until meeting and exceeding our clients needs and expectations.  With over 10 years of combined experience, Paradigm Sports Management combines athletic, academic, and professional knowledge to create a formidable synergy, providing a full-service agency with an unmatched efficiency.  Our hands on approach provide our clients with strategic, analytical and honest advice in both our clients' playing and business careers. We aim to develop life long relationships, whereby our clients can always count on Paradigm Sports Management to be their partner, confidant and friend on and off their respective field.</p>
            </div>
        </div>
    </div>
</section>
<div class="container-fluid-about">
	<div class="row">
		<div class="row-about"><%= image_tag 'team.jpg', class: 'img-responsive' %></div>
		<div class="row-about"><%= image_tag 'team.jpg', class: 'img-responsive' %></div>

		<!-- Add the extra clearfix for only the required viewport -->
		<div class="clearfix visible-xs-block"></div>

		<div class="row-about"><%= image_tag 'team.jpg', class: 'img-responsive' %></div>
		<div class="row-about"><%= image_tag 'team.jpg', class: 'img-responsive' %></div>
	</div>
</div>

app/views/pages/basketball.html.erb
<% title "Basketball | Paradigm Sports Management" %>

<section class="header-16-sub home-content home-content-header basketball" id="header-content">
	<div class="background"></div>
	<div id="h-16-pt-main" class="page-transitions pt-perspective">
		<div class="v-center pt-page pt-page-1 pt-page-current">
			<div>
				<div class="container">
					<div class="hero-unit">
						<div id="logo-main">
							<h1>BASKETBALL<br>MANAGEMENT</h1>
						</div>
					</div>
				</div>
			</div>
			<span class="scroll-btn">
				<a href="#">
					<span class="mouse"><span> </span>
					</span>
				</a>
			</span>
		</div>
	</div>
</section>

<section class="content-32-basketball">
	<div class="container">
		<div class="row">
			<div class="col-sm-10 col-sm-offset-1">
				<p>Paradigm has a full service basketball management division that specializes on the transition of players entering or departing the United States. Through our experience in representing top level professional athletes in the NFL, MMA, FIBA and MLS, we are able to provide services that most soccer firms lack. Our international experience working with professional soccer players allows us to provide our clients an advantage when negotiating with clubs. Our expertise focuses on contract negotiation, loans, transfers and securing tryouts.</p>
			</div>
		</div>
	</div>
</section>

<section class="content-31" style="padding-bottom:0px;">
	<div class="container">
		<div class="row">
			<div class="number">1</div>
			<div class="col-sm-8 col-sm-offset-2">
				<h3>CONTRACT NEGOTIATIONS</h3>
				<p>Paradigm consists of attorneys and MBAs with over 25 years of corporate and sports contractual experience.  Paradigm holds extensive contract negotiations experience both domestically and internationally across numerous leagues. Paradigm Basketball provides an extensive, detailed oriented negotiation on behalf of clients. We will work endlessly to ensure our client’s contract reflects your ability and value to your organization.</p>
			</div>
		</div>
		<div class="row">
			<div class="number">2</div>
			<div class="col-sm-8 col-sm-offset-2">
				<div id="pt-1" class="page-transitions pt-perspective">
					<div class="pt-page pt-page-current">
						<h3>PERFORMANCE MANAGEMENT</h3>
						<p>No agent works miracles. It is the persistence and hard work of every player that allows them to succeed. There are however, very important strategic measure that Paradigm provides clients before, during and after their playing career.</p>
						<br>
						<h4>Player Performance Evaluations</h4>
						<h4>Access to Top Off-Season Training Preparation</h4>
						<h4>Mental Conditioning & Sports Psychology</h4>
					</div>
				</div>
			</div>
		</div>
		<div class="row">
			<div class="number">3</div>
			<div class="col-sm-8 col-sm-offset-2">
				<div id="pt-2" class="page-transitions pt-perspective">
					<div class="pt-page pt-page-current">
						<h3>LIFESTYLE MANAGEMENT</h3>
						<p>Paradigm focuses on the establishment of personal relationships with our clients. This allows us to provide a quality lifestyle services specifically based on individual requirements. Our Basketball division provides transparent and consistent service in all areas of their life:</p>
						<br>
						<p>- Relocation Assistance via The Dingman Group<br>- Extensive experience with US and International tax requirements<br>- Legal Counseling from in house general counsel<br>- Financial  Management services via trusted external advisors</p>
					</div>
				</div>
			</div>
		</div>
	</div>
</section>

<section class="projects-2-basketball">
	<div class="project-1 v-center-basketball">
	</div>
</section>

<section class="content-32-basketball">
	<div class="container">
		<div class="row">
			<div class="col-sm-10 col-sm-offset-1">
				<h3>MARKETING MANAGEMENT</h3>
				<p>Paradigm provides an integrated marketing plan, developed exclusively for each client. Our team of marketing professionals analyze the personality, the position and performance of our clients to maximize ancillary income. We aggressively pursue marketing opportunities for each clients through:</p>
				<br>
				<p>Brand Building and Management<br>- Public Relations<br>- Sponsorship<br>- Endorsements<br>- Local and national media campaigns<br>- Social Media Activation<br>- Seminar and Speaking Appearances</p>
			</div>
		</div>
	</div>
</section>


<script>
	(function($) {
		$('.v-center-basketball').each(function() {
			if (! isMobile.any() ) {
				$(this).parallax('50%', 0.3, true);
			} else {
				$(this).css('background-attachment', 'initial')
			}
		})
	}(jQuery));
</script>

app/views/pages/contact.html.erb
<% title "Contact | Paradigm Sports Management" %>

<section class="header-16-sub home-content home-content-header contact" id="header-content">
  <div class="background"></div>
  <div id="h-16-pt-main" class="page-transitions pt-perspective">
    <div class="v-center pt-page pt-page-1 pt-page-current">
      <div>
        <div class="container">
          <div class="hero-unit">
            <div id="logo-main">
              <h3>LEARN MORE OF</h3>
              <h1>WHAT WE DO</h1>
            </div>
          </div>
        </div>
      </div>
      <span class="scroll-btn">
        <a href="#">
          <span class="mouse"><span> </span>
        </span>
      </a>
    </span>
  </div>
</div>
</section>

app/views/pages/football.html.erb
<% title "Football | Paradigm Sports Management" %>

<section class="header-16-sub home-content home-content-header football" id="header-content">
	<div class="background"></div>
	<div id="h-16-pt-main" class="page-transitions pt-perspective">
		<div class="v-center pt-page pt-page-1 pt-page-current">
			<div>
				<div class="container">
					<div class="hero-unit">
						<div id="logo-main">
							<h1>FOOTBALL<br>MANAGEMENT</h1>
						</div>
					</div>
				</div>
			</div>
			<span class="scroll-btn">
				<a href="#">
					<span class="mouse"><span> </span>
					</span>
				</a>
			</span>
		</div>
	</div>
</section>

<section class="content-32-football">
	<div class="container">
		<div class="row">
			<div class="col-sm-10 col-sm-offset-1">
				<p>Paradigm has a full service football management division that provides unparalleled individual attention to our clients on and off the field. Paradigms establishes every client’s brand identity and maximize earning potential before, during and after their professional career.</p>
			</div>
		</div>
	</div>
</section>

<section class="content-31" style="padding-bottom:0px;">
	<div class="container">
		<div class="row">
			<div class="number">1</div>
			<div class="col-sm-8 col-sm-offset-2">
				<h3>CONTRACT NEGOTIATIONS</h3>
				<p>Paradigm consists of attorneys and MBAs with over 25 years of corporate and NFL contractual experience. Paradigm provides an extensive, detailed oriented negotiation on behalf of clients. We will work endlessly to ensure our client’s contract reflects your ability and value to your organization.</p>
			</div>
		</div>
		<div class="row">
			<div class="number">2</div>
			<div class="col-sm-8 col-sm-offset-2">
				<div id="pt-1" class="page-transitions pt-perspective">
					<div class="pt-page pt-page-current">
						<h3>PERFORMANCE MANAGEMENT</h3>
						<p>No agent works miracles. It is the persistence and hard work of every player that allows them to succeed in their promotion. There are however, very important strategic measures that Paradigm provides clients before, during and after their soccer career.</p>
						<br>
						<h4>Player Performance Evaluations</h4>
						<p>By leveraging Paradigm’s established relationship across the NFL and CFL, it allow us to provide candid feedback on player performance leading up to the bowl game and pre-draft workout season.</p>
						<br>
						<h4>Combine/Pro Day Preparation</h4>
						<p>Acess to the most decorated training facilities in the country to offer elite preparation training for Combine, Pro Day and team workouts.</p>
						<br>
						<h4>Mental Conditioning & Sports Psychology</h4>
						<p>We work with theBrian Cain, one of the most sought after mental conditioning and peak performance coaches, and is one of the top speakers, consultants and coaches when it comes to maximizing your performance. He is also the #1 best-selling author of five sports psychology books and award-winning audio and video training programs. Over 400 of his clients have gone on to get drafted into Major League Baseball, including over 25 in the first round.  He has helped train top picks in the NFL, NHL and NBA drafts.  In addition, he has worked closely in the corner of five Ultimate Fighting Championship World Champions, including UFC Superstar Georges St. Pierre, numerous Major League Baseball All-Stars, The Washington Nationals Organization and Team USA Baseball.</p>
					</div>
				</div>
			</div>
		</div>
		<div class="row">
			<div class="number">3</div>
			<div class="col-sm-8 col-sm-offset-2">
				<div id="pt-2" class="page-transitions pt-perspective">
					<div class="pt-page pt-page-current">
						<h3>LIFESTYLE MANAGEMENT</h3>
						<p>Paradigm focuses on the establishment of personal relationships with our clients. This allows us to provide a quality lifestyle services specifically based on individual requirements. Our Football division provides transparent and consistent service in all areas of their life:</p>
						<br>
						<p>- Relocation Assistance via The Dingman Group<br>- Legal Counseling from in house general counsel<br>- Financial Management services via trusted external advisors</p>
					</div>
				</div>
			</div>
		</div>
	</div>
</section>

<section class="projects-2-football">
	<div class="project-1 v-center-football">
	</div>
</section>

<section class="content-32-football">
	<div class="container">
		<div class="row">
			<div class="col-sm-10 col-sm-offset-1">
				<h3>MARKETING MANAGEMENT</h3>
				<p>Paradigm provides an integrated marketing plan, developed exclusively for each client. Our team of marketing professionals analyze the personality, the position and performance of our clients to maximize ancillary income. We aggressively pursue marketing opportunities for each clients through:</p>
				<br>
				<p>Brand Building and Management<br>- Public Relations<br>- Sponsorship<br>- Endorsements<br>- Local and national media campaigns<br>- Social Media Activation<br>- Seminar and Speaking Appearances</p>
			</div>
		</div>
	</div>
</section>


<script>
	(function($) {
		$('.v-center-football').each(function() {
			if (! isMobile.any() ) {
				$(this).parallax('50%', 0.3, true);
			} else {
				$(this).css('background-attachment', 'initial')
			}
		})
	}(jQuery));
</script>

app/views/pages/media.html.erb
<% title "Media | Paradigm Sports Management" %>

<section class="header-16-sub home-content home-content-header media" id="header-content">
  <div class="background"></div>
  <div id="h-16-pt-main" class="page-transitions pt-perspective">
    <div class="v-center pt-page pt-page-1 pt-page-current">
      <div>
        <div class="container">
          <div class="hero-unit">
            <div id="logo-main">
              <h3>LEARN MORE OF</h3>
              <h1>WHAT WE DO</h1>
            </div>
          </div>
        </div>
      </div>
      <span class="scroll-btn">
        <a href="#">
          <span class="mouse"><span> </span>
        </span>
      </a>
    </span>
  </div>
</div>
</section>

app/views/pages/services.html.erb
<% title "Services | Paradigm Sports Management" %>

<section class="header-16-sub home-content home-content-header services" id="header-content">
	<div class="background"></div>
	<div id="h-16-pt-main" class="page-transitions pt-perspective">
		<div class="v-center pt-page pt-page-1 pt-page-current">
			<div>
				<div class="container">
					<div class="hero-unit">
						<div id="logo-main">
							<h3>FIND OUT ALL OF OUR</h3>
							<h1>SERVICES</h1>
						</div>
					</div>
				</div>
			</div>
			<span class="scroll-btn">
				<a href="#">
					<span class="mouse"><span> </span>
					</span>
				</a>
			</span>
		</div>
	</div>
</section>

<!-- projects-2 -->
<section class="projects-2">
	<div class="project-1 v-center">
	  <div>
	    <!--v-center-->
	    <div class="container">
	      <h1>SOCCER MANAGEMENT</h1>
	      <%= link_to 'Learn More', soccer_path, class:'btn btn-inverse-service' %>
	    </div>
	    <!--/.container-->
	  </div>
	  <!--/v-center-->
	</div>
	<div class="project-2 v-center">
	  <div>
	    <!--v-center-->
	    <div class="container">
	      <h1>BASKETBALL MANAGEMENT</h1>
	      <%= link_to 'Learn More', basketball_path, class:'btn btn-inverse-service' %>
	    </div>
	    <!--/.container-->
	  </div>
	  <!--/v-center-->
	</div>
	<div class="project-3 v-center">
	  <div>
	    <!--v-center-->
	    <div class="container">
	      <h1>MMA MANAGEMENT</h1>
	      <%= link_to 'Learn More', mma_path, class:'btn btn-inverse-service' %>
	    </div>
	    <!--/.container-->
	  </div>
	  <!--/v-center-->
	</div>
		<div class="project-4 v-center">
	  <div>
	    <!--v-center-->
	    <div class="container">
	      <h1>FOOTBALL MANAGEMENT</h1>
	      <%= link_to 'Learn More', football_path, class:'btn btn-inverse-service' %>
	    </div>
	    <!--/.container-->
	  </div>
	  <!--/v-center-->
	</div>
		<div class="project-5 v-center">
	  <div>
	    <!--v-center-->
	    <div class="container">
	      <h1>SPORTS MARKETING</h1>
	     	<%= link_to 'Learn More', sports_marketing_path, class:'btn btn-inverse-service' %>
	    </div>
	    <!--/.container-->
	  </div>
	  <!--/v-center-->
	</div>
</section>

app/views/pages/sports-marketing.html.erb
<% title "Sports Marketing | Paradigm Sports Management" %>

<section class="header-16-sub home-content home-content-header marketing" id="header-content">
	<div class="background"></div>
	<div id="h-16-pt-main" class="page-transitions pt-perspective">
		<div class="v-center pt-page pt-page-1 pt-page-current">
			<div>
				<div class="container">
					<div class="hero-unit">
						<div id="logo-main">
							<h1>SPORTS</h1>
							<br>
							<h1>MARKETING</h1>
						</div>
					</div>
				</div>
			</div>
			<span class="scroll-btn">
				<a href="#">
					<span class="mouse"><span> </span>
				</span>
			</a>
		</span>
	</div>
</div>
</section>

<section class="content-32-marketing">
	<div class="container">
		<div class="row">
			<div class="col-sm-10 col-sm-offset-1">
				<p>Right message, right time and right location. At Paradigm, we understand the importance of specialized and precision marketing. Nowhere is this more important than within sports marketing.</p>
				<br>
				<p>We specialize in creating a brand identity for clients from all sports, backgrounds and success levels. Paradigm has demonstrated the ability to create dynamic and engaging campaigns that allow brands to become a literal part of property being used as a channel. Moreover, alignment of values and congruent messages between the brand and property is essential.</p>
				<br>
				<p>Paradigm will enhance our clients profile and brand by engaging with a number of media vehicle with the common goal of developing our client’s image in the most positive manner.</p>
			</div>
		</div>
	</div>
</section>

app/views/users/_user.html.erb
<td><%= link_to user.name, user %></td>
<td><%= link_to user.email, user %></td>

app/views/users/index.html.erb
<div class="container">
  <div class="row">
    <h3>Users</h3>
    <div class="column">
      <table class="table">
        <tbody>
          <% @users.each do |user| %>
            <tr>
              <%= render user %>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<h3>User</h3>
<p>Name: <%= @user.name if @user.name %></p>
<p>Email: <%= @user.email if @user.email %></p>

app/views/visitors/index.html.erb
<h3>Welcome</h3>
<p><%= link_to 'Users:', users_path %> <%= User.count %> registered</p>